### ISSUE TITLE
Feature Request: Create profile asset

### ISSUE THREAD

**Issue by Paulmski** [Paulmski/Discord-Bot#17]
We need a profile picture for the bot. If you have a suggestion for a profile please leave a comment here. After reviewing the submitted assets we'll pick one and integrate it into the next version!

**Comment by tuanyvan** [comment]
I chopped up something in PowerPoint. I highly encourage other submissions for the profile picture too since I used a lot of .svg files from the Office 365 asset library.

It is a little generic and not unique to Lakehead University, but seeing the school's [corporate identity page](https://www.lakeheadu.ca/about/branding/guidelines/lakehead-identity/identity) makes editing the school logo seem frowned upon. As well, HD versions of the school logo are only given upon request.

<img width="270" alt="First Profile Picture" src="https://user-images.githubusercontent.com/93796037/145733223-98c51ba4-a78e-4a4a-8eb5-ead27a3ffa97.png">
<img width="270" alt="First profile picture preview" src="https://user-images.githubusercontent.com/93796037/145733224-0b48d00d-b7c5-455b-bc90-28de023bdc73.png">
<img width="270" alt="Second Profile Picture" src="https://user-images.githubusercontent.com/93796037/145733225-f49f301f-f289-46cf-b060-cdc2290a594d.png">
<img width="270" alt="Second profile picture preview" src="https://user-images.githubusercontent.com/93796037/145733226-a084c46d-c8c6-4d7a-b422-0a5127a1f654.png">

**Comment by Paulmski** [comment]
Thanks for the submission! If we get enough people active on this issue perhaps we'll do a vote.
