### ISSUE TITLE
Create templates

### ISSUE THREAD

**Issue by Paulmski** [Paulmski/Discord-Bot#18]
To make creating issues easier, to make and read. It would be useful to create templates/checklist for different kinds of issues, bug reports, and pull requests.

For example, a pull request template could be:
1. What is the purpose of the pull request?
2. Is this feature or fix complete? (otherwise, a separate branch will be created for it)
3. Does your code compile?
4. Have you added the appropriate tags?

In the long run, this will help streamline interactions and will allow for less wasted time trying to figure out what a person is trying to do or say.

**Comment by tuanyvan** [comment]
The templates for feature requests, bug reports, and pull requests have been made. However, [I believe they need to be pushed to the `main` branch in order to be usable](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates#:~:text=You%20must%20create%20templates%20on%20the%20repository%27s%20default%20branch.).

Later down the line, we could also create [form-based issue templates using YAML](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms).

**Comment by Paulmski** [comment]
Great! It can be added in the next merge to the main branch
