### ISSUE TITLE
Bug: Inaccurate weekday on assignment announcements

### ISSUE THREAD

**Issue by tuanyvan** [Paulmski/Discord-Bot#65]
## Describe the bug...
Inside both announcements and `!list` calls, the weekday in which the assignment is said to be due is not correct.

## To Reproduce...
1. Call the `!list` command for any or all courses.
2. Notice the unexpected weekday. In the following screenshot, January 16th, 2022 should be on a Sunday. However, it says it is a Tuesday.

![image](https://user-images.githubusercontent.com/93796037/149152061-63f0a9ea-a681-497c-aa79-2bdc0c068f9f.png)

## Expected Behavior
The correct weekday should be two days behind what is written by the Bot (i.e. Tuesday => Sunday, etc.). This behavior will differ with every year, but nonetheless is clearly indicative of an incorrect `datetime` object.

## Cause
Tuesday happens to be the weekday on January 16th, 1900.

**Comment by Paulmski** [comment]
Part of this bug is unrelated to the code base, but consistently formatting dates on the spreadsheet. It is important to include the year that the assignment is due, because the bot cannot always assume it is due this year. 

Assignment due dates must be formated full month number day, year e.g. "January 2, 2022".
